require "tenebrae.options"
require "tenebrae.keymaps"
require "tenebrae.plugins"
require "tenebrae.colorscheme"
require "tenebrae.cmp"
require "tenebrae.lsp"
require "tenebrae.telescope"
require "tenebrae.treesitter"
require "tenebrae.autopairs"
require "tenebrae.gitsigns"
require "tenebrae.nvim-tree"
require "tenebrae.bufferline"
require "tenebrae.toggleterm"
require "tenebrae.lualine"
require "tenebrae.impatient"
require "tenebrae.indendline"

